version: '2'
services:
  web-pozos:
    image: php:apache
    depends_on:
      - api
    environment:
      - USERNAME=toto
      - PASSWORD=python
    ports:
      - "8080:80"
    volumes:
      - ./website:/var/www/html
    networks:
      - api-pozos

  api:
    image: api-pozos:1
    ports:
      - "5000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - api-pozos

networks:
 api-pozos:
